name: "Samsung AC Proxy"
version: "1.0.0"
slug: "samsung_ac_proxy"
description: "A secure TLS proxy to bridge Home Assistant Climate IP with older Samsung AC units."
arch:
  - amd64
  - aarch64
  - armv7
startup: "services"
boot: "auto"
ports:
  2878/tcp: 2878
options:
  ac_ip: "192.168.0.70"
schema:
  ac_ip: str
